name: build-tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        compiler: [ clang, gcc ]
  
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies    
      run: |
        sudo apt-get update;sudo apt-get install -y libbz2-dev liblzma-dev libcurl4-openssl-dev
        git clone --depth=1 https://github.com/ANGSD/smallBam.git
        git clone --depth=1 --recursive https://github.com/samtools/htslib
    - name: Compile dependencies (htslib)
      run: |
        cd htslib;make    
    - name: Compile main program (angsd and misc/*)
      run: |
        make HTSSRC=htslib/
    - name: Run Unit tests
      run: |
        make test BAMDIR=./smallBam/
